services:
    MauticPlugin\RoundRobinOwnersBundle\Model\Action\AssignRoundRobinOwnerAction:
        arguments:
            $dispatcher: '@event_dispatcher'
            $config: '@mautic.helper.core_parameters'
            $translator: '@translator'
            $logger: '@logger'
            $userRepository: '@mautic.user.repository.user'
            $entityManager: '@doctrine.orm.entity_manager'
            $emailModel: '@mautic.email.model.email'
            $mailer: '@mailer'
        tags:
            - { name: mautic.action, alias: round_robin_owner, label: 'Round Robin Owners' }
